Repository MPAS-Dev/MPAS-Tools, pull requests merged in 2024-11, with the labels that each got.

#587 Fix the local gh-pages directory in docs workflow
  .github/workflows/docs_workflow.yml
Labels: bug, conda package

#589 Add dependabot workflow
  .github/dependabot.yml
Labels: continuous integration

#590 Port barotropic streamfunction from MPAS-Analysis
  conda_package/docs/api.rst
  conda_package/docs/index.rst
  conda_package/docs/ocean/streamfunction.rst
  conda_package/mpas_tools/ocean/__init__.py
  conda_package/mpas_tools/ocean/barotropic_streamfunction.py
  conda_package/mpas_tools/ocean/depth.py
Labels: enhancement
